apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: replica-count.yaml
- path: configmap-patch.yaml

images:
- name: api-gateway
  newName: placeholder
  newTag: placeholder
- name: event-producer
  newName: placeholder
  newTag: placeholder
- name: stream-processor
  newName: placeholder
  newTag: placeholder
- name: websocket-server
  newName: placeholder
  newTag: placeholder