apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: replica-count.yaml
- path: configmap-patch.yaml

images:
- name: api-gateway
  newName: 865189667386.dkr.ecr.us-east-1.amazonaws.com/real-time-platform/api-gateway
  newTag: 27323e72a8a3b39ab9fe5fa8b4e77b7699ec1196
- name: event-producer
  newName: 865189667386.dkr.ecr.us-east-1.amazonaws.com/real-time-platform/event-producer
  newTag: 27323e72a8a3b39ab9fe5fa8b4e77b7699ec1196
- name: stream-processor
  newName: 865189667386.dkr.ecr.us-east-1.amazonaws.com/real-time-platform/stream-processor
  newTag: 27323e72a8a3b39ab9fe5fa8b4e77b7699ec1196
- name: websocket-server
  newName: 865189667386.dkr.ecr.us-east-1.amazonaws.com/real-time-platform/websocket-server
  newTag: 27323e72a8a3b39ab9fe5fa8b4e77b7699ec1196
